nord_fox = {
    'bg':           "#2e3440",
    'fg':           "#b9bfca",
    'fg_gutter':    "#4b5668",
    'black':        "#3b4252",
    'red':          "#bf616a",
    'green':        "#a3be8c",
    'yellow':       "#ebcb8b",
    'blue':         "#81a1c1",
    'magenta':      "#b48ead",
    'cyan':         "#88c0d0",
    'white':        "#e5e9f0",
    'orange':       "#c9826b",
    'pink':         "#bf88bc",
}
